name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compilar Projeto
      run: g++ -O3 ordenacao.cpp -o benchmark

    - name: Rodar Teste Rápido
      run: ./benchmark 10000
